name: lintr

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  lintr:
    name: Run lintr

    # This is a hack to get an "environment variable" that can be accessed by
    # "runs-on"; normally env variables can only be accessed at the "step" level
    strategy:
      matrix:
        os: [ubuntu-20.04]
        rversion: [4.0.2]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev -y

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.rversion }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}-R-${{ matrix.rversion }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Install lintr
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make install-lintr

      - name: Run lintr
        run: make lintr
